### PR TITLE
Add support for PKCS12 keystore files.

### PR DESCRIPTION
**Pull request by ChristopherSchultz**

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Hi @ChristopherSchultz ,

Thanks for the contribution - looks useful.  Note that this repository is archive of legacy code - but given this module gets some use through the link at Nagios exchange, it's still worthwhile to merge in contributions.

Just a few minor comments:

1. I see that the passwordFile `-P` argument is only used with PKCS12 - that is correct, PEM certificate files are not encrypted (`openssl x509 -passin` is only used with SIGNING).  But could you please change the option documentation (in `print_help(), L277) to explicitly state it is only used with PKCS12?

2. The PEM file check passes the`$additional` args received via `-a`.  I first thought I'd ask you to pass that to the `openssl pkcs12` invocations as well... but I see that with PKCS12, you had to split the openssl invocation into two parts: first parse PKCS12, then parse the PEM produced by the first step - and you are passing the `$additional` args to the second step.  This looks good to me, I am just stating it here for the record.

3. The script file unfortunately uses mixed indentation - in case of the list of options, a tab followed by 6 spaces.  I noticed the diff of your changes was showing indentation thrown off - could you please use the same in your changes to the option list?

It's just these two knits I found (1 and 3) - otherwise, it looks all good to me and ready to merge.  

Thanks for your contribution!

Cheers,
Vlad

**Comment by ChristopherSchultz** [comment]
Sure, I'll address those issues right away. Apologies for the indentation. I know that's always annoying.

**Comment by ChristopherSchultz** [comment]
> Note that this repository is archive of legacy code - but given this module gets some use through the link at Nagios exchange, it's still worthwhile to merge in contributions.

I appreciate that.

>     1. I see that the passwordFile `-P` argument is only used with PKCS12

Documented no-op for PED/DER files.

>     2. The PEM file check passes the`$additional` args received via `-a`.  I first thought I'd ask you to pass that to the `openssl pkcs12` invocations as well... but I see that with PKCS12, you had to split the openssl invocation into two parts: first parse PKCS12, then parse the PEM produced by the first step - and you are passing the `$additional` args to the second step.  This looks good to me, I am just stating it here for the record.

ACK

>     3. The script file unfortunately uses mixed indentation.

Fixed.

Thanks for the review and, presumably, the accepted PR :)

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the contribution @ChristopherSchultz  - merging now.

**Pull request merged**
